import { ESexualActivityLevel } from "Api/Types/enums/ESexualActivityLevel"

export type LifeHabitsInfoDTO = {
    patientId: number,
    mealsPerDay: number,
    waterCupsPerDay: number,
    eatingAndWaterObs?: string,
    bladderEliminationsCharacteristic: string,
    bladderEliminationTimesPerDay: number,
    hasPainOnBladderEliminations: boolean,
    intestinalEliminationsCharacteristic: string,
    intestinalEliminationTimesPerDay: number,
    hasPainOnIntestinalEliminations: boolean,
    isAlcoholUser: boolean,
    alcoholQuantityObs?: string,
    isSmoker: boolean,
    cigarretesPerDay?: number,
    isFormerSmoker: boolean,
    timeWithoutSmoking?: string,
    isIllicitDrugsUser: boolean,
    illicitDrugsUsingObs?: string,
    hasSatisfactorySleepingTime: boolean,
    sleepingHoursPerNight: number,
    sleepingTimeObs?: string,
    physicalActivityIds: number[],
    physicalActivitiesObservation?: string,
    physicalActivityTimesPerWeek: number,
    leisureObservation?: string,
    sexualActivityLevel: ESexualActivityLevel,
    sexualPartnersQuantity: number,
    contraceptiveMethodIds: number[],
    hasPrEP: boolean,
    hasPEP: boolean,
    isPreservativeUser: boolean
}